# Generated by Django 3.1.7 on 2021-04-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='main_story',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
