# Generated by Django 3.1.7 on 2021-04-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters_app', '0002_auto_20210417_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='main_story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='middle_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='nickname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='surname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
